'use client';

import { useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase-client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Loader2, Upload, ArrowLeft } from 'lucide-react';
import { DatePicker } from '@/components/ui/date-picker';
import { useZipLookup } from '@/hooks/useZipLookup';
import Link from 'next/link';

const SERVICE_TYPES = [
  { value: 'hhg_local', label: 'HHG Local' },
  { value: 'hhg_long_distance', label: 'HHG Long Distance' },
  { value: 'commercial', label: 'Commercial' },
  { value: 'storage_in', label: 'Storage In' },
  { value: 'storage_out', label: 'Storage Out' },
  { value: 'freight', label: 'Freight' },
  { value: 'other', label: 'Other' },
];

export default function PostPickupPage() {
  const router = useRouter();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const { lookup } = useZipLookup();

  const [formData, setFormData] = useState({
    // Reference
    internal_reference: '',
    // Customer info
    customer_name: '',
    customer_phone: '',
    // Pickup date range
    pickup_date_start: '',
    pickup_date_end: '',
    // Origin
    origin_address: '',
    origin_city: '',
    origin_state: '',
    origin_zip: '',
    share_origin_address: true, // Share full address once matched
    // Destination
    destination_address: '',
    destination_city: '',
    destination_state: '',
    destination_zip: '',
    // Load details
    cubic_feet: '',
    rate_per_cuft: '',
    balance_due: '',
    service_type: 'hhg_long_distance',
    notes: '',
  });

  const handleChange = (field: string, value: string | boolean) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const handleOriginZipBlur = useCallback(async () => {
    if (formData.origin_zip.length === 5) {
      const result = await lookup(formData.origin_zip);
      if (result) {
        setFormData((prev) => ({
          ...prev,
          origin_city: prev.origin_city || result.city,
          origin_state: prev.origin_state || result.stateAbbr,
        }));
      }
    }
  }, [formData.origin_zip, lookup]);

  const handleDestinationZipBlur = useCallback(async () => {
    if (formData.destination_zip.length === 5) {
      const result = await lookup(formData.destination_zip);
      if (result) {
        setFormData((prev) => ({
          ...prev,
          destination_city: prev.destination_city || result.city,
          destination_state: prev.destination_state || result.stateAbbr,
        }));
      }
    }
  }, [formData.destination_zip, lookup]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setError(null);

    try {
      const supabase = createClient();

      // Get current user
      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      // Get user's workspace company
      const { data: workspaceCompany } = await supabase
        .from('companies')
        .select('id')
        .eq('owner_id', user.id)
        .eq('is_workspace_company', true)
        .maybeSingle();

      if (!workspaceCompany) throw new Error('No company found. Please complete your company profile first.');

      // Create the pickup posting
      // Note: load_number is auto-generated by database trigger in LD-000001 format
      const { data: insertedLoad, error: insertError } = await supabase.from('loads').insert({
        owner_id: user.id,
        company_id: workspaceCompany.id,
        posted_by_company_id: workspaceCompany.id,
        // job_number will be set from load_number after insert
        internal_reference: formData.internal_reference || null,
        load_type: 'pickup',
        posting_type: 'pickup',
        posting_status: 'posted',
        posted_at: new Date().toISOString(),
        service_type: formData.service_type,
        // Marketplace visibility - required for load to appear on load board
        is_marketplace_visible: true,
        posted_to_marketplace_at: new Date().toISOString(),
        load_status: 'pending',
        // Customer info stored in pickup contact (optional)
        pickup_contact_name: formData.customer_name || null,
        pickup_contact_phone: formData.customer_phone || null,
        // Pickup date range
        pickup_date_start: formData.pickup_date_start || null,
        pickup_date_end: formData.pickup_date_end || null,
        pickup_date: formData.pickup_date_start || null,
        // Origin (address optional, city/state/zip required)
        pickup_address_line1: formData.origin_address || null,
        pickup_city: formData.origin_city,
        pickup_state: formData.origin_state,
        pickup_zip: formData.origin_zip,
        pickup_postal_code: formData.origin_zip,
        // Marketplace display columns
        origin_city: formData.origin_city,
        origin_state: formData.origin_state,
        origin_zip: formData.origin_zip,
        share_origin_address: formData.share_origin_address,
        // Destination (address optional, city/state/zip required)
        dropoff_address_line1: formData.destination_address || null,
        dropoff_city: formData.destination_city,
        dropoff_state: formData.destination_state,
        dropoff_postal_code: formData.destination_zip,
        delivery_address_line1: formData.destination_address || null,
        delivery_city: formData.destination_city,
        delivery_state: formData.destination_state,
        delivery_postal_code: formData.destination_zip,
        // Marketplace display columns
        destination_city: formData.destination_city,
        destination_state: formData.destination_state,
        destination_zip: formData.destination_zip,
        // Load details - set both column variants
        cubic_feet: parseFloat(formData.cubic_feet) || 0,
        estimated_cuft: parseFloat(formData.cubic_feet) || 0,
        rate_per_cuft: parseFloat(formData.rate_per_cuft) || 0,
        balance_due: parseFloat(formData.balance_due) || 0,
        linehaul_amount: parseFloat(formData.balance_due) || 0,
        company_rate: parseFloat(formData.balance_due) || 0,
        notes: formData.notes,
      });

      if (insertError) throw insertError;

      // Redirect to posted jobs
      router.push('/dashboard/posted-jobs');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to post pickup');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto px-6 pt-4 space-y-4">
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="icon" asChild>
          <Link href="/dashboard/posted-jobs">
            <ArrowLeft className="h-4 w-4" />
          </Link>
        </Button>
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Post a Pickup</h1>
          <p className="text-sm text-muted-foreground/90">
            Carrier will collect the balance from the customer.
          </p>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-4">
        {error && (
          <div className="bg-destructive/10 text-destructive p-3 rounded-lg text-sm">
            {error}
          </div>
        )}

        {/* Customer Information + Pickup Window in 2 columns */}
        <div className="grid gap-4 lg:grid-cols-2">
          <Card className="rounded-lg">
            <CardHeader className="pb-3">
              <CardTitle className="text-base font-medium tracking-tight">Reference & Customer</CardTitle>
              <CardDescription className="text-xs">Your internal reference + optional customer info</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="space-y-1.5">
                <Label htmlFor="internal_reference" className="text-sm">Internal Reference / Job #</Label>
                <Input
                  id="internal_reference"
                  value={formData.internal_reference}
                  onChange={(e) => handleChange('internal_reference', e.target.value)}
                  placeholder="Your CRM job number (optional)"
                  className="h-9"
                />
              </div>
              <div className="grid gap-3 sm:grid-cols-2">
                <div className="space-y-1.5">
                  <Label htmlFor="customer_name" className="text-sm">Customer Name</Label>
                  <Input
                    id="customer_name"
                    value={formData.customer_name}
                    onChange={(e) => handleChange('customer_name', e.target.value)}
                    placeholder="John Smith"
                    className="h-9"
                  />
                </div>
                <div className="space-y-1.5">
                  <Label htmlFor="customer_phone" className="text-sm">Customer Phone</Label>
                  <Input
                    id="customer_phone"
                    type="tel"
                    value={formData.customer_phone}
                    onChange={(e) => handleChange('customer_phone', e.target.value)}
                    placeholder="(555) 123-4567"
                    className="h-9"
                  />
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="rounded-lg">
            <CardHeader className="pb-3">
              <CardTitle className="text-base font-medium tracking-tight">Pickup Window</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-3 sm:grid-cols-2">
              <div className="space-y-1.5">
                <Label htmlFor="pickup_date_start" className="text-sm">Earliest Date *</Label>
                <DatePicker
                  name="pickup_date_start"
                  placeholder="Select date"
                  onChange={(value) => handleChange('pickup_date_start', value)}
                  className="h-9"
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="pickup_date_end" className="text-sm">Latest Date *</Label>
                <DatePicker
                  name="pickup_date_end"
                  placeholder="Select date"
                  onChange={(value) => handleChange('pickup_date_end', value)}
                  className="h-9"
                />
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Origin & Destination in 2 columns */}
        <div className="grid gap-4 lg:grid-cols-2">
          <Card className="rounded-lg">
            <CardHeader className="pb-3">
              <CardTitle className="text-base font-medium tracking-tight">Origin (Pickup)</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="grid gap-2 grid-cols-3">
                <div className="space-y-1.5">
                  <Label htmlFor="origin_zip" className="text-sm">ZIP *</Label>
                  <Input
                    id="origin_zip"
                    value={formData.origin_zip}
                    onChange={(e) => handleChange('origin_zip', e.target.value)}
                    onBlur={handleOriginZipBlur}
                    placeholder="10001"
                    required
                    className="h-9"
                  />
                </div>
                <div className="space-y-1.5">
                  <Label htmlFor="origin_city" className="text-sm">City *</Label>
                  <Input
                    id="origin_city"
                    value={formData.origin_city}
                    onChange={(e) => handleChange('origin_city', e.target.value)}
                    placeholder="New York"
                    required
                    className="h-9"
                  />
                </div>
                <div className="space-y-1.5">
                  <Label htmlFor="origin_state" className="text-sm">State *</Label>
                  <Input
                    id="origin_state"
                    value={formData.origin_state}
                    onChange={(e) => handleChange('origin_state', e.target.value)}
                    placeholder="NY"
                    maxLength={2}
                    required
                    className="h-9"
                  />
                </div>
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="origin_address" className="text-sm">Address</Label>
                <Input
                  id="origin_address"
                  value={formData.origin_address}
                  onChange={(e) => handleChange('origin_address', e.target.value)}
                  placeholder="123 Main St (optional)"
                  className="h-9"
                />
              </div>
              {formData.origin_address && (
                <div className="flex items-center space-x-2">
                  <Checkbox
                    id="share_origin_address"
                    checked={formData.share_origin_address}
                    onCheckedChange={(checked) => handleChange('share_origin_address', !!checked)}
                  />
                  <Label htmlFor="share_origin_address" className="text-sm font-normal text-muted-foreground">
                    Share full address with carrier once matched
                  </Label>
                </div>
              )}
            </CardContent>
          </Card>

          <Card className="rounded-lg">
            <CardHeader className="pb-3">
              <CardTitle className="text-base font-medium tracking-tight">Destination (Delivery)</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="grid gap-2 grid-cols-3">
                <div className="space-y-1.5">
                  <Label htmlFor="destination_zip" className="text-sm">ZIP *</Label>
                  <Input
                    id="destination_zip"
                    value={formData.destination_zip}
                    onChange={(e) => handleChange('destination_zip', e.target.value)}
                    onBlur={handleDestinationZipBlur}
                    placeholder="90001"
                    required
                    className="h-9"
                  />
                </div>
                <div className="space-y-1.5">
                  <Label htmlFor="destination_city" className="text-sm">City *</Label>
                  <Input
                    id="destination_city"
                    value={formData.destination_city}
                    onChange={(e) => handleChange('destination_city', e.target.value)}
                    placeholder="Los Angeles"
                    required
                    className="h-9"
                  />
                </div>
                <div className="space-y-1.5">
                  <Label htmlFor="destination_state" className="text-sm">State *</Label>
                  <Input
                    id="destination_state"
                    value={formData.destination_state}
                    onChange={(e) => handleChange('destination_state', e.target.value)}
                    placeholder="CA"
                    maxLength={2}
                    required
                    className="h-9"
                  />
                </div>
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="destination_address" className="text-sm">Address</Label>
                <Input
                  id="destination_address"
                  value={formData.destination_address}
                  onChange={(e) => handleChange('destination_address', e.target.value)}
                  placeholder="456 Oak Ave (optional)"
                  className="h-9"
                />
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Load Details & Pricing */}
        <Card className="rounded-lg">
          <CardHeader className="pb-3">
            <CardTitle className="text-base font-medium tracking-tight">Load Details & Pricing</CardTitle>
            <CardDescription className="text-xs">
              Balance due is what the carrier will collect from the customer.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="grid gap-3 sm:grid-cols-4">
              <div className="space-y-1.5">
                <Label htmlFor="cubic_feet" className="text-sm">Est. CUFT *</Label>
                <Input
                  id="cubic_feet"
                  type="number"
                  min="1"
                  value={formData.cubic_feet}
                  onChange={(e) => handleChange('cubic_feet', e.target.value)}
                  placeholder="500"
                  required
                  className="h-9"
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="rate_per_cuft" className="text-sm">Rate/CUFT ($) *</Label>
                <Input
                  id="rate_per_cuft"
                  type="number"
                  min="0"
                  step="0.01"
                  value={formData.rate_per_cuft}
                  onChange={(e) => handleChange('rate_per_cuft', e.target.value)}
                  placeholder="5.00"
                  required
                  className="h-9"
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="balance_due" className="text-sm">Balance Due ($) *</Label>
                <Input
                  id="balance_due"
                  type="number"
                  min="0"
                  step="0.01"
                  value={formData.balance_due}
                  onChange={(e) => handleChange('balance_due', e.target.value)}
                  placeholder="2500.00"
                  required
                  className="h-9"
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="service_type" className="text-sm">Service Type *</Label>
                <Select
                  value={formData.service_type}
                  onValueChange={(value) => handleChange('service_type', value)}
                >
                  <SelectTrigger id="service_type" className="h-9">
                    <SelectValue placeholder="Select" />
                  </SelectTrigger>
                  <SelectContent>
                    {SERVICE_TYPES.map((type) => (
                      <SelectItem key={type.value} value={type.value}>
                        {type.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="notes" className="text-sm">Notes</Label>
              <Textarea
                id="notes"
                value={formData.notes}
                onChange={(e) => handleChange('notes', e.target.value)}
                placeholder="Any special instructions, access issues, etc."
                rows={2}
                className="text-sm"
              />
            </div>
          </CardContent>
        </Card>

        {/* Submit */}
        <div className="flex justify-end gap-3">
          <Button type="button" variant="outline" size="sm" asChild>
            <Link href="/dashboard/posted-jobs">Cancel</Link>
          </Button>
          <Button type="submit" size="sm" disabled={isSubmitting}>
            {isSubmitting ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Posting...
              </>
            ) : (
              <>
                <Upload className="mr-2 h-4 w-4" />
                Post Pickup
              </>
            )}
          </Button>
        </div>
      </form>
    </div>
  );
}
